# Generated by Django 3.2.5 on 2021-07-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management_Sytem_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='total_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='report_card',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
