# Generated by Django 3.2.5 on 2021-07-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management_Sytem_app', '0002_auto_20210728_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Student_Management_Sytem_app.courses'),
        ),
    ]
