# Generated by Django 3.2.5 on 2021-08-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management_Sytem_app', '0004_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('myList', models.TextField(null=True)),
                ('teacher_id', models.TextField()),
                ('test_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Management_Sytem_app.courses')),
                ('session_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Management_Sytem_app.sessionyearmodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Management_Sytem_app.students')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
