# Generated by Django 3.2.5 on 2021-08-18 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management_Sytem_app', '0005_auto_20210818_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsresult',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsresult',
            name='teacher_id',
            field=models.IntegerField(),
        ),
    ]
