# Generated by Django 3.2.5 on 2021-08-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management_Sytem_app', '0006_auto_20210818_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsresult',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
